# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a4fd8e2e6cffad2e63f3d8d658aa3e9259c3ea6652a372f37d09451a80b0cdd0b3b009fc02f829a7e044fe0ac48eee42318441f953d3db08fd673983f2fc87f4

test:
  secret_key_base: 6cbfefea59eed230543cf77d44077c1bbe00cd33a0e673a6b83e14d7e4033bff593c3772b5071e338242b35d6ad03298eba5212751cc2c7d916e258e61618df5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
